[package]
name = "tuzios"
version = "0.1.0"
authors = ["Michael Matuzak <mmatuzak@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[profile.release]
panic = "abort"

[dependencies]
volatile = "0.1.0"
spin = "0.4.5"
